trigger:
  branches:
    include:
      - master
    exclude:
      - azure-pipeline.yml

pool: 
  name: 'Default'
  demands:
  - agent.os -equals Linux

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '905fc28f-8f4e-4f00-bcad-78b7445665d1'
  imageRepository: 'sql-connection/sql-connection'
  containerRegistry: 'sgsin01acr01.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: 'latest'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
   
    - task: CmdLine@2
      inputs:
        script: |
          echo > Dockerfile
          
          cat > Dockerfile <<EOF
          FROM python:3
          WORKDIR /app
          ADD requirements.txt .
          ADD app.py .
          
          # # install FreeTDS and dependencies
          # RUN apt-get update \
          #   && apt-get install unixodbc -y \
          #   && apt-get install unixodbc-dev -y \
          #   && apt-get install freetds-dev -y \
          #   && apt-get install freetds-bin -y \
          #   && apt-get install tdsodbc -y \
          #   && apt-get install --reinstall build-essential -y
          # # populate "ocbcinst.ini" as this is where ODBC driver config sits
          # RUN echo "[FreeTDS]\n\
          # Description = FreeTDS Driver\n\
          # Driver = /usr/lib/x86_64-linux-gnu/odbc/libtdsodbc.so\n\
          # Setup = /usr/lib/x86_64-linux-gnu/odbc/libtdsS.so" >> /etc/odbcinst.ini
          #Pip command without proxy setting
          RUN pip install -r requirements.txt
          su
          curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -

          #Download appropriate package for the OS version
          #Choose only ONE of the following, corresponding to your OS version

          #Debian 9
          #curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list

          #Debian 10
          #curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list

          #Debian 11
          curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list

          exit
          apt-get update -y
          ACCEPT_EULA=Y apt-get install -y msodbcsql18
          # optional: for bcp and sqlcmd
          ACCEPT_EULA=Y apt-get install -y mssql-tools18
          echo 'export PATH="$PATH:/opt/mssql-tools18/bin"' >> ~/.bashrc
          source ~/.bashrc
          # optional: for unixODBC development headers
          apt-get install -y unixodbc-dev
          # optional: kerberos library for debian-slim distributions
          apt-get install -y libgssapi-krb5-2

          COPY /modifyHostsFile.sh /home/user/modifyHostsFile.sh
          RUN chmod +x /home/user/modifyHostsFile.sh
          CMD ["/bin/bash", "/home/user/run.sh"]
          
          CMD ["python","-i","app.py"]
         
          EOF
    

    - task: CmdLine@2
      inputs:
        script: |
          mkdir manifests    
          
          echo > cronjob.yml
          
          cat > cronjob.yml <<EOF
          # apiVersion: batch/v1beta1
          # #apiVersion: batch/v1
          # kind: CronJob
          # metadata:
          #   name: sql-connection
          # spec:
          #   schedule: "*/1 * * * *" 
          #   jobTemplate:
          #     spec:
          #       template:
          #         spec:
          #           containers:
          #           - name: sql-connection
          #             image:  sgsin01acr01.azurecr.io/sql-connection/sql-connection:latest
          #             imagePullPolicy: Always
          #           restartPolicy: OnFailure
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: sql-connection
          spec: 
            template:
              metadata:
                name: sql-connection
              spec:
                  containers:
                  - name: sql-connection
                    image:  sgsin01acr01.azurecr.io/sql-connection/sql-connection:latest
                    imagePullPolicy: Always
                  restartPolicy: OnFailure
          EOF
          echo > service.yml
          
          cat > service.yml <<EOF
          apiVersion: v1
          kind: Service
          metadata:
            name: sql-connection
          spec:
            type: ClusterIP
            ports:
              - port: 1433
            selector:
              app: sql-connection
          EOF

          

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)


    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(Pipeline.Workspace)'
        artifact: 'sqlConnection'
        publishLocation: 'pipeline'
        
    - task: CmdLine@2
      inputs:
        script: 'docker rmi -f $(docker images -a -q)'